<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array $config
 *
 * @link https://github.com/DDMAL/diva.js/wiki/Settings
 */

$config['id'] =  isset($config['id']) ? $config['id'] : 'diva';
$configJson = json_encode($config, 448);
$script = <<<JS
$(document).ready(function() {
    $('#{$config['id']}').diva($configJson).data('diva');
});
JS;
$this->headScript()->appendScript($script);

?>

<div id="<?= $config['id'] ?>" class="diva viewer"></div>
